language: node_js
node_js:
- 0.1
env:
  global:
  - ci=true
  - secure: Fp8LhomKFFOFMaTblgZrVbXHm//Fb/KV9gYNBYej+7SWgctQNssfks/3kKtNpBnO//V8hlNWNUJUMAqLd8bw4vOqa/SM57Zb1mFwYPs/oHbpf4RUHQCHAtRT5Fb0toaulLyScjM4JmyaIZQ6PVjVbEF8zvdB5pMkNxMmbCOQiQ4=
  - secure: bfOObptzg9vHOr5Gm1qrKwd2AppjG9kvWUp7SiG9l2VHZK4FK+1K5Yax2K2EL1qZHuksT3HesgBt1qC1njLEhdVxDmNDTpZxTaTxVYCq/GFgtC1989uHibPIf7qJqPAASfoTrBLON1UY20XXFv6ygpmm6IKFK4b+APy6koWGKuQ=
addons:
  sauce_connect: true
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm test || npm run unit-tests'